name: Prepare environment config

inputs:
  env_variables:
    description: 'JSON string object with information about variables and mappings. See more in the documentation.'
    required: true

runs:
  using: 'node16'
  main: 'index.js'