name: Prepare environment config

inputs:
  env_file:
    description: 'Path to environment file. This has higher priority than the one defined in the CI environment config.'
    required: false
  env_file_stub:
    description: 'Path to environment stub file. This has higher priority than the one defined in the CI environment config.'
    required: false
  env_variables:
    description: 'JSON string object with information about variables and mappings. See more in the documentation.'
    required: true

runs:
  using: 'node16'
  main: 'index.js'