name: Update Changelog

inputs:
  changelog_path:
    description: 'Path to the changelog file'
    required: false
    default: 'CHANGELOG.md'
  target_version:
    description: 'Version to add to the changelog'
    required: true
  mode:
    description: 'Can be "normal" or "raw". Latter one will simply yield changelog with no file normalization'
    required: false
    default: 'normal'
  offset:
    description: 'Offset for the start tag to get changelog since'
    required: false
    default: '0'
runs:
  using: 'node16'
  main: 'index.js'
