name: 'mysql-import'

inputs:
  dump_file_path:
    description: 'Path to the DB dump'
    required: true
  db_name:
    description: 'DB name to export dump from'
    required: true
  host:
    description: 'MySQL server address'
    required: false
    default: 'localhost'
  username:
    description: 'MySQL server username'
    required: false
    default: 'root'
  password:
    description: 'MySQL server password'
    required: false
    default: 'root'
  port:
    description: 'MySQL port'
    required: false
    default: '3306'

runs:
  using: "composite"
  steps:
    - name: MySQL import
      run: |
        mysql -u ${{inputs.username}} -p${{inputs.password}} --host ${{inputs.host}} --port ${{inputs.port}} ${{ inputs.db_name }} < ${{ inputs.dump_file_path }}
      shell: bash
