name: 'Publish Github Release'

inputs:
  release_version:
    required: true
    type: string
  github_release:
    required: false
    default: true
    type: boolean
  dist_folder:
    required: false
    default: 'dist'
    type: string
  UNIQUES_GITHUB_ACCESS_TOKEN:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - uses: montudor/action-zip@v1
      if: ${{ inputs.github_release == true }}
      with:
        args: zip -qq -r dist.zip ${{ inputs.dist_folder }}

    - uses: marvinpinto/action-automatic-releases@latest
      if: ${{ inputs.github_release == true }}
      with:
        repo_token: ${{ inputs.UNIQUES_GITHUB_ACCESS_TOKEN }}
        automatic_release_tag: ${{ inputs.release_version }}
        prerelease: false
        title: Release ${{ inputs.release_version }}
        files: dist.zip